"""initial schema

Revision ID: 5c3d32b0126d
Revises:
Create Date: 2026-08-17 17:41:00.094695
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5c3d32b0126d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "container_types",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("tare_weight_g", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "name", name="uq_container_type_name"),
    )
    with op.batch_alter_table("container_types", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_container_types_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "meal_prep_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PORTIONING", "READY", "CANCELLED", name="batchstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("identification_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("kcal_total", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("protein_total", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("fat_total", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("carbs_total", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("total_net_weight_g", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "idempotency_key", name="uq_batch_idempotency"),
    )
    with op.batch_alter_table("meal_prep_batches", schema=None) as batch_op:
        batch_op.create_index("ix_batches_owner_created", ["owner_id", "created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_meal_prep_batches_owner_id"), ["owner_id"], unique=False
        )

    op.create_table(
        "products",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("canonical_name", sa.String(length=300), nullable=False),
        sa.Column("brand", sa.String(length=160), nullable=True),
        sa.Column("variant", sa.String(length=200), nullable=True),
        sa.Column("gtin", sa.String(length=32), nullable=True),
        sa.Column("net_quantity", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("net_unit", sa.String(length=16), nullable=True),
        sa.Column("kcal_per_100", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("protein_per_100", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("fat_per_100", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("carbs_per_100", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column(
            "nutrition_status",
            sa.Enum(
                "PENDING",
                "MATCHED",
                "VERIFIED",
                "ESTIMATED",
                "AMBIGUOUS",
                "FAILED",
                name="enrichmentstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("nutrition_source_url", sa.Text(), nullable=True),
        sa.Column("image_source_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "gtin", name="uq_products_owner_gtin"),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_products_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(
            "ix_products_owner_name", ["owner_id", "canonical_name"], unique=False
        )

    op.create_table(
        "receipts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("fiscal_fn", sa.String(length=32), nullable=False),
        sa.Column("fiscal_fd", sa.String(length=32), nullable=False),
        sa.Column("fiscal_fp", sa.String(length=32), nullable=False),
        sa.Column(
            "operation",
            sa.Enum("SALE", "RETURN", name="receiptoperation", native_enum=False),
            nullable=False,
        ),
        sa.Column("merchant_name", sa.String(length=300), nullable=False),
        sa.Column("merchant_inn", sa.String(length=20), nullable=False),
        sa.Column("purchased_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("source_message_id", sa.String(length=255), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_id", "fiscal_fn", "fiscal_fd", "fiscal_fp", name="uq_receipt_fiscal"
        ),
    )
    with op.batch_alter_table("receipts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_receipts_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(
            "ix_receipts_owner_purchased", ["owner_id", "purchased_at"], unique=False
        )

    op.create_table(
        "meal_prep_containers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("container_type_id", sa.Uuid(), nullable=True),
        sa.Column("public_code", sa.String(length=24), nullable=False),
        sa.Column("gross_weight_g", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("tare_weight_g", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("net_weight_g", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("remaining_weight_g", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "READY",
                "PARTIAL",
                "CONSUMED",
                "DISCARDED",
                name="containerstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("kcal", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("protein", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("fat", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("carbs", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["batch_id"], ["meal_prep_batches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["container_type_id"], ["container_types.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_code", name="uq_container_public_code"),
    )
    with op.batch_alter_table("meal_prep_containers", schema=None) as batch_op:
        batch_op.create_index("ix_containers_owner_status", ["owner_id", "status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_meal_prep_containers_batch_id"), ["batch_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_meal_prep_containers_owner_id"), ["owner_id"], unique=False
        )

    op.create_table(
        "product_aliases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("merchant_inn", sa.String(length=20), nullable=False),
        sa.Column("raw_name", sa.String(length=500), nullable=False),
        sa.Column("normalized_name", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_id", "merchant_inn", "normalized_name", name="uq_product_alias_lookup"
        ),
    )
    with op.batch_alter_table("product_aliases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_product_aliases_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_product_aliases_product_id"), ["product_id"], unique=False
        )

    op.create_table(
        "receipt_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("raw_name", sa.String(length=500), nullable=False),
        sa.Column("normalized_name", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("unit_price_minor", sa.Integer(), nullable=False),
        sa.Column("total_minor", sa.Integer(), nullable=False),
        sa.Column("gtin", sa.String(length=32), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column(
            "enrichment_status",
            sa.Enum(
                "PENDING",
                "MATCHED",
                "VERIFIED",
                "ESTIMATED",
                "AMBIGUOUS",
                "FAILED",
                name="enrichmentstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("receipt_id", "position", name="uq_receipt_line_position"),
    )
    with op.batch_alter_table("receipt_lines", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_receipt_lines_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(
            "ix_receipt_lines_owner_status", ["owner_id", "enrichment_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_receipt_lines_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_receipt_lines_receipt_id"), ["receipt_id"], unique=False
        )

    op.create_table(
        "consumptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("container_id", sa.Uuid(), nullable=False),
        sa.Column("consumed_weight_g", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("kcal", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("protein", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("fat", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("carbs", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("glucotracker_meal_id", sa.Uuid(), nullable=True),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["container_id"], ["meal_prep_containers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("consumptions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_consumptions_container_id"), ["container_id"], unique=False
        )
        batch_op.create_index(
            "ix_consumptions_owner_consumed", ["owner_id", "consumed_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_consumptions_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "enrichment_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("receipt_line_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "MATCHED",
                "VERIFIED",
                "ESTIMATED",
                "AMBIGUOUS",
                "FAILED",
                name="enrichmentstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["receipt_line_id"], ["receipt_lines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "receipt_line_id", name="uq_enrichment_receipt_line"),
    )
    with op.batch_alter_table("enrichment_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_enrichment_jobs_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(
            "ix_enrichment_status_created", ["status", "created_at"], unique=False
        )

    op.create_table(
        "inventory_lots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("receipt_line_id", sa.Uuid(), nullable=True),
        sa.Column("display_name", sa.String(length=500), nullable=False),
        sa.Column("original_quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("remaining_quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "AVAILABLE",
                "RESERVED",
                "DEPLETED",
                "DISCARDED",
                "RETURNED",
                name="inventorystatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("purchased_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["receipt_line_id"], ["receipt_lines.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("receipt_line_id"),
    )
    with op.batch_alter_table("inventory_lots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_inventory_lots_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_inventory_lots_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index("ix_inventory_owner_status", ["owner_id", "status"], unique=False)

    op.create_table(
        "batch_ingredients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("lot_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("display_name", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("kcal", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("protein", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("fat", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("carbs", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("nutrition_estimated", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["batch_id"], ["meal_prep_batches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lot_id"], ["inventory_lots.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("batch_ingredients", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_batch_ingredients_batch_id"), ["batch_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_batch_ingredients_lot_id"), ["lot_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_batch_ingredients_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_batch_ingredients_product_id"), ["product_id"], unique=False
        )

    op.create_table(
        "inventory_transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("lot_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "PURCHASE",
                "RESERVE",
                "RELEASE",
                "CONSUME",
                "RETURN",
                "ADJUST",
                name="inventorytransactionkind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("delta_quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("reference_type", sa.String(length=40), nullable=False),
        sa.Column("reference_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lot_id"], ["inventory_lots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inventory_transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_inventory_transactions_lot_id"), ["lot_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_transactions_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(
            "ix_inventory_tx_owner_created", ["owner_id", "created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError("Fridge migrations are forward-only")
