"""classify receipt inventory lines

Revision ID: 9b206caa3fb0
Revises: 5c3d32b0126d
Create Date: 2026-08-17 19:04:22.677316
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9b206caa3fb0"
down_revision: str | None = "5c3d32b0126d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("receipt_lines", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("package_quantity", sa.Numeric(precision=12, scale=3), nullable=True)
        )
        batch_op.add_column(sa.Column("package_unit", sa.String(length=16), nullable=True))
        batch_op.add_column(
            sa.Column(
                "inventory_effect",
                sa.Boolean(),
                server_default=sa.true(),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError("Fridge migrations are forward-only")
